module.exports = {
	products: [
		{
			_id: '1',
			name: 'SteelSeries Apex Pro Mechanical Gaming Keyboard – Adjustable Actuation Switches – World’s Fastest Mechanical Keyboard – OLED Smart Display – RGB Backlit',
			category: 'Gaming',
			image: '/images/product-1.jpg',
			price: 149.99,
			brand: 'SteelSeries',
			rating: 4.5,
			numberReviews: 10,
			countInStock: 0,
			description: 'product 1',
		},
		{
			_id: '2',
			name: 'Logitech MK270 Wireless Keyboard and Mouse Combo for Windows, 2.4 GHz Wireless, Compact Mouse, 8 Multimedia and Shortcut Keys, 2-Year Battery Life, for PC, Laptop, Black',
			category: 'Multimedia',
			image: '/images/product-2.jpg',
			price: 33.99,
			brand: 'Logitech',
			rating: 4.5,
			numberReviews: 10,
			countInStock: 6,
			description: 'product 2',
		},
		{
			_id: '3',
			name: 'Corsair K60 RGB Pro Mechanical Gaming Keyboard - CHERRY Mechanical Keyswitches - Durable AluminumFrame - Customizable Per-Key RGB Backlighting',
			category: 'Gaming',
			image: '/images/product-3.jpg',
			price: 69.99,
			brand: 'Corsair',
			rating: 5,
			numberReviews: 10,
			countInStock: 6,
		},
		{
			_id: '4',
			name: 'Logitech K270 Wireless Keyboard for Windows, 2.4 GHz Wireless, Full-Size, Number Pad, 8 Multimedia Keys, 2-Year Battery Life, Compatible with PC, Laptop',
			category: 'Gaming',
			image: '/images/product-4.jpg',
			price: 119.99,
			brand: 'Logitech',
			rating: 4,
			numberReviews: 10,
			countInStock: 6,
		},
		{
			_id: '5',
			name: 'Logitech MX Keys Advanced Wireless Illuminated Keyboard, Tactile Responsive Typing, Backlighting, Bluetooth, USB-C, Apple macOS, Microsoft Windows, Linux, iOS, Android, Metal Build - Graphite',
			category: 'Gaming',
			image: '/images/product-5.jpg',
			price: 119.99,
			brand: 'Logitech',
			rating: 4.5,
			numberReviews: 10,
			countInStock: 6,
		},
		{
			_id: '6',
			name: 'Wireless Keyboard Mouse Combo, cimetech Compact Full Size Wireless Keyboard and Mouse Set Less Noise Keys 2.4G Ultra-Thin Sleek Design for Windows, Computer, PC, Notebook, Laptop (Bright Pink)',
			category: 'Business',
			image: '/images/product-6.jpg',
			price: 34.99,
			brand: 'Cimetech',
			rating: 4,
			numberReviews: 10,
			countInStock: 6,
		},
		{
			_id: '7',
			name: 'Verbatim Slimline Full Size Wired Keyboard USB Plug-and-Play - Compatible with PC, Laptop - Black',
			category: 'Gaming',
			image: '/images/product-7.jpg',
			price: 10,
			brand: 'Verbatim',
			rating: 4.5,
			numberReviews: 10,
			countInStock: 6,
		},
		{
			_id: '8',
			name: 'CORSAIR STRAFE RGB MK.2 Mechanical Gaming Keyboard - USB Passthrough - Linear and Quiet - Cherry MX Red Switch - RGB LED Backlit-17.6 x 6.61 x 1.57 inches',
			category: 'Business',
			image: '/images/product-8.jpg',
			price: 112.2,
			brand: 'CORSAIR',
			rating: 4.5,
			numberReviews: 10,
			countInStock: 6,
		},
	],
};
